tests:
	make test-orbit
	make test-curved-orbit

test-orbit:
	make -C ./orbit

test-curved-orbit:
	make -C ./curved-orbit

clean:
	make cleanorbit
	make cleancurved-orbit

cleanorbit:
	make -C ./orbit clean

cleancurved-orbit:
	make -C ./curved-orbit clean
