include ../../Makeheader

springpluscoulomb: springpluscoulomb.cc ../../libmd.cc ../../libmd.h ../../libmd-src/*
	$(CC) $(CCFLAGS) -o springpluscoulomb springpluscoulomb.cc

clean:
	rm springpluscoulomb
