include ../../Makeheader

freelyjointedchain freelyjointedchain2: freelyjointedchain.cc freelyjointedchain2.cc ../../libmd.cc ../../libmd.h ../../libmd-src/*
	$(CC) $(CCFLAGS) -o freelyjointedchain freelyjointedchain.cc
	$(CC) $(CCFLAGS) -o freelyjointedchain2 freelyjointedchain2.cc

clean:
	rm freelyjointedchain
	rm freelyjointedchain2
