include ../../Makeheader

randomspring: randomspring.cc ../../libmd.cc ../../libmd.h ../../libmd-src/* ../../tools/springio/springio.cc ../../tools/springio/PointSystem2d/*
	$(CC) $(CCFLAGS) -o randomspring randomspring.cc

clean:
	rm randomspring
