examples:
	make example-orbit
	make example-curved-orbit
	make example-randomspring
	make example-libmdspring
	make example-dampedrandomspring
	make example-springpluscoulomb
	make example-hertzianpulse
	make example-freelyjointedchain
	make example-dimers
	make example-glassnetwork

example-orbit:
	make -C ./orbit

example-curved-orbit:
	make -C ./curved-orbit

example-randomspring:
	make -C ./randomspring

example-libmdspring:
	make -C ./libmdspring

example-springpluscoulomb:
	make -C ./springpluscoulomb

example-hertzianpulse:
	make -C ./hertzianpulse

example-freelyjointedchain:
	make -C ./freelyjointedchain

example-dimers:
	make -C ./dimers

example-dampedrandomspring:
	make -C ./dampedrandomspring

example-glassnetwork:
	make -C ./glassnetwork

clean:
	make cleanorbit
	make cleancurved-orbit
	make cleanrandomspring
	make cleanlibmdspring
	make cleanspringpluscoulomb
	make cleanhertzianpulse
	make cleanfreelyjointedchain
	make cleandimers
	make cleandampedrandomspring
	make cleanglassnetwork

cleanorbit:
	make -C ./orbit clean

cleancurved-orbit:
	make -C ./curved-orbit clean

cleanrandomspring:
	make -C ./randomspring clean

cleanlibmdspring:
	make -C ./libmdspring clean

cleanspringpluscoulomb:
	make -C ./springpluscoulomb clean

cleanhertzianpulse:
	make -C ./hertzianpulse clean

cleanfreelyjointedchain:
	make -C ./freelyjointedchain clean

cleandimers:
	make -C ./dimers clean

cleandampedrandomspring:
	make -C ./dampedrandomspring clean

cleanglassnetwork:
	make -C ./glassnetwork clean
