examples:
	make example-orbit
	make example-curved-orbit
	make example-randomspring
	make example-springpluscoulomb
	make example-hertzianpulse

example-orbit:
	make -C ./orbit

example-curved-orbit:
	make -C ./curved-orbit

example-randomspring:
	make -C ./randomspring

example-springpluscoulomb:
	make -C ./springpluscoulomb

example-hertzianpulse:
	make -C ./hertzianpulse

examples-piston:
	make -C ./piston

clean:
	make cleanorbit
	make cleancurved-orbit
	make cleanrandomspring
	make cleanspringpluscoulomb
	make cleanhertzianpulse
	make cleanpiston

cleanorbit:
	make -C ./orbit clean

cleancurved-orbit:
	make -C ./curved-orbit clean

cleanrandomspring:
	make -C ./randomspring clean

cleanspringpluscoulomb:
	make -C ./springpluscoulomb clean

cleanhertzianpulse:
	make -C ./hertzianpulse clean

cleanpiston:
	make -C ./piston clean
