include ../../Makeheader

dissipativespring: dissipativespring.cc ../../libmd.cc ../../libmd.h ../../libmd-src/*
	$(CC) $(CCFLAGS) -o dissipativespring dissipativespring.cc

clean:
	rm dissipativespring
