include ../../Makeheader

glass-shear: glass-shear.cc ../../libmd.cc ../../libmd.h ../../libmd-src/* ../../tools/springio/springio.cc ../../tools/springio/PointSystem2d/*
	$(CC) $(CCFLAGS) -o glass-shear glass-shear.cc

clean:
	rm glass-shear
