include ../../Makeheader

dampedrandomspring: dampedrandomspring.cc springio.cc ../../libmd.cc ../../libmd.h ../../libmd-src/*
	$(CC) $(CCFLAGS) -o dampedrandomspring dampedrandomspring.cc

clean:
	rm dampedrandomspring
