include ../../Makeheader

dampedrandomspring: dampedrandomspring.cc ../../libmd.cc ../../libmd.h ../../libmd-src/* ../../tools/springio/*
	$(CC) $(CCFLAGS) -o dampedrandomspring dampedrandomspring.cc

clean:
	rm dampedrandomspring
