include ../../Makeheader

dissipativenetwork: dissipativenetwork.cc ../../libmd.cc ../../libmd.h ../../libmd-src/* ../../tools/springio/*
	$(CC) $(CCFLAGS) -o dissipativenetwork dissipativenetwork.cc

clean:
	rm dissipativenetwork
